<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
		<TargetFramework>net8.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <SelfContained>true</SelfContained>
    <RootNamespace>pdfforge.PDFCreator.ErrorReport</RootNamespace>
    <UseWPF>true</UseWPF>
    <SatelliteResourceLanguages>None</SatelliteResourceLanguages>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Description>Error reporting tool for PDFCreator</Description>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Windows.ThemeInfoAttribute">
      <_Parameter1>System.Windows.ResourceDictionaryLocation.None</_Parameter1>
      <_Parameter1_IsLiteral>true</_Parameter1_IsLiteral>
      <_Parameter2>System.Windows.ResourceDictionaryLocation.SourceAssembly</_Parameter2>
      <_Parameter2_IsLiteral>true</_Parameter2_IsLiteral>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="PDFCreator.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ControlzEx">
      <Version>5.0.2</Version>
    </PackageReference>
    <PackageReference Include="MahApps.Metro">
      <Version>2.4.10</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf">
      <Version>1.1.122</Version>
    </PackageReference>
    <PackageReference Include="Sentry">
      <Version>3.41.4</Version>
    </PackageReference>
    <PackageReference Include="System.Text.Json">
      <Version>8.0.5</Version>
    </PackageReference>
  </ItemGroup>
</Project>
