<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\Utilities\Utilities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp">
      <Version>4.7</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Web.WebView2">
      <Version>1.0.3240.44</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Web.WebView2.DevToolsProtocolExtension">
      <Version>1.0.2901</Version>
    </PackageReference>
    <PackageReference Include="System.Text.Json">
      <Version>8.0.5</Version>
    </PackageReference>
  </ItemGroup>
</Project>