<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>pdfforge.PDFCreator.UI.PDFCreatorCOM</RootNamespace>
    <AssemblyName>PDFCreator.PDFCreatorCOM</AssemblyName>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <EnableComHosting>true</EnableComHosting>
    <SatelliteResourceLanguages>None</SatelliteResourceLanguages>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.InteropServices.ComVisibleAttribute">
      <_Parameter1>true</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.InteropServices.GuidAttribute">
      <_Parameter1>8b8d2928-eaaf-492d-8da5-e06b358d8826</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Conversion\Processing\ITextProcessing\ITextProcessing.csproj" />
    <ProjectReference Include="..\COM\COM.csproj" />
  </ItemGroup>
<ItemGroup>
<InternalsVisibleTo Include="COM.UnitTest" />
<InternalsVisibleTo Include="COM.IntegrationTest" />
</ItemGroup>
<ItemGroup>
  <PackageReference Include="Microsoft.NETCore.Platforms">
    <Version>7.0.4</Version>
  </PackageReference>
  <PackageReference Include="Microsoft.NETCore.Targets">
    <Version>5.0</Version>
  </PackageReference>
  <PackageReference Include="Microsoft.Win32.Registry">
    <Version>5.0</Version>
  </PackageReference>
  <PackageReference Include="NLog">
    <Version>5.4</Version>
  </PackageReference>
  <PackageReference Include="SimpleInjector">
    <Version>5.4.6</Version>
  </PackageReference>
  <PackageReference Include="System.ComponentModel">
    <Version>4.3</Version>
  </PackageReference>
  <PackageReference Include="System.Runtime">
    <Version>4.3.1</Version>
  </PackageReference>
  <PackageReference Include="System.Security.AccessControl">
    <Version>6.0.1</Version>
  </PackageReference>
  <PackageReference Include="System.Security.Permissions">
    <Version>8.0</Version>
  </PackageReference>
  <PackageReference Include="System.Security.Principal.Windows">
    <Version>5.0</Version>
  </PackageReference>
  <PackageReference Include="System.Windows.Extensions">
    <Version>8.0</Version>
  </PackageReference>
  <PackageReference Include="SystemInterface">
    <Version>9.10.0</Version>
  </PackageReference>
  <PackageReference Include="SystemWrapper">
    <Version>9.10.0</Version>
  </PackageReference>
</ItemGroup>
</Project>
