<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <AssemblyVersion>6.3.0.0</AssemblyVersion>
    <FileVersion>6.3.0.0</FileVersion>
    <InformationalVersion>6.3.0.0</InformationalVersion>
  </PropertyGroup>
</Project>